version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - .:/code
            - /code/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - 3000:8080
    